from typing import Optional, Protocol

from lxml.etree import _Element


class TmxElement(Protocol):
    def __init__(self, XmlElement: Optional[_Element] = None, **attribs) -> None: ...
    def to_element(self) -> _Element: ...
    def to_string(self) -> str: ...
    @property
    def attrib(self) -> dict[str, str]: ...
